{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-video",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.3.aar",
          "url": "camera-video-1.3.3.aar",
          "size": 361507,
          "sha512": "53e7503e94a3ea7d5d3e1077b87ab2029fe4dfe7eae122aa35763963d1310492c285b2545ad81b163361accc6d706c224693743a06044be503f5a9f10eceabfc",
          "sha256": "b703fe9f71314ce319a65bbf222e3d6acc01a85e994cf5c75743a8387cc0efe6",
          "sha1": "4617d4cde13bdba09941711d2b137acb3453d072",
          "md5": "0a73245c77e22d7d12d6c5e93a5e4676"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.3.aar",
          "url": "camera-video-1.3.3.aar",
          "size": 361507,
          "sha512": "53e7503e94a3ea7d5d3e1077b87ab2029fe4dfe7eae122aa35763963d1310492c285b2545ad81b163361accc6d706c224693743a06044be503f5a9f10eceabfc",
          "sha256": "b703fe9f71314ce319a65bbf222e3d6acc01a85e994cf5c75743a8387cc0efe6",
          "sha1": "4617d4cde13bdba09941711d2b137acb3453d072",
          "md5": "0a73245c77e22d7d12d6c5e93a5e4676"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.3-sources.jar",
          "url": "camera-video-1.3.3-sources.jar",
          "size": 262785,
          "sha512": "a604c3567164066cd505bb76bd0c15937977e3c68ccd3f85f6b772bce10610b2a0ef00872e8e699c16d06849c78ecc6bf5c9dec9e0a00a1b64fc83c0574dfbe9",
          "sha256": "b550fd75244b2cc11a76d1d6f7556a37fe0788971e3a83a5a1924ff05288dd70",
          "sha1": "744f04a0efc95a4c086127d37f550e80450a2bc1",
          "md5": "3d35f456cee452a89516f4b40c8b97ed"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.3-versionMetadata.json",
          "url": "camera-video-1.3.3-versionMetadata.json",
          "size": 10368,
          "sha512": "f6b3f4a1dbcf58b295b939a95f87e79c6bbada5370cd53bb025d71894d97d696b0f42145ec6a925c783f45d02f3874ac23c491b9f08eb06fc06b0f1a96509c08",
          "sha256": "4677296a86aaf7b7263836c53a59e8020cd8b283e29ab8d701be4cea343e9289",
          "sha1": "7c5da9e728622f9b531f1d909f9255067abf6226",
          "md5": "ce6b2859a4c6bb4e76619ae20dc4ebf3"
        }
      ]
    }
  ]
}