{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.3.3.aar",
          "url": "camera-core-1.3.3.aar",
          "size": 804865,
          "sha512": "aa58e205cdef169a643d4c1ef0c5ea816b3e168e62ad18be69b4c5be3cd50afbea28d12e1f28a7d6fd54609f77cab19e7be354e5474b23b226a5aad9986a4368",
          "sha256": "dc0d068465f91604ddda8b9e35af6f8977d231e625459e882b78f3e3e5b2f743",
          "sha1": "b63c04971627f86513a2925c356683eb4d79b948",
          "md5": "f575f4ba6329631cb14b4ca5572d8b0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.3.3.aar",
          "url": "camera-core-1.3.3.aar",
          "size": 804865,
          "sha512": "aa58e205cdef169a643d4c1ef0c5ea816b3e168e62ad18be69b4c5be3cd50afbea28d12e1f28a7d6fd54609f77cab19e7be354e5474b23b226a5aad9986a4368",
          "sha256": "dc0d068465f91604ddda8b9e35af6f8977d231e625459e882b78f3e3e5b2f743",
          "sha1": "b63c04971627f86513a2925c356683eb4d79b948",
          "md5": "f575f4ba6329631cb14b4ca5572d8b0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.3.3-sources.jar",
          "url": "camera-core-1.3.3-sources.jar",
          "size": 616502,
          "sha512": "2a5f2907840e1abe62c5dd37e914fca026f22f30248ec904b171ded3749521d7272286291f317957eaa6ea263e4512a0cc8c4cf3850bb28ead19058660915b3c",
          "sha256": "5fd470a6b0f0ed48df4c93889df5fb274d11d2f8dfaeae86d059f894d0c8ebe3",
          "sha1": "49732469f6e59afc7aceafc501a1e701549bf124",
          "md5": "0321f7d54bbb8001e452c60f79310a9a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.3.3-versionMetadata.json",
          "url": "camera-core-1.3.3-versionMetadata.json",
          "size": 31297,
          "sha512": "bc6bd346e9b434ee00d77dc7562cc66750ffc3ac96b6388437aa1aebf415f887715accff567289b00efb9618ab39d76975f606508826243ee0db5178a15cf548",
          "sha256": "30d10e6914e7a94b02cd637d8af6fbead149871911b0ebaca1ab9fbdb46edb90",
          "sha1": "bf5b5590a32e57da5eee87e1793cd13f5058eac7",
          "md5": "c905397956e315aba3b76945c38b7dc7"
        }
      ]
    }
  ]
}