{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.3.aar",
          "url": "camera-lifecycle-1.3.3.aar",
          "size": 22530,
          "sha512": "bb00b714decc3a1995ad60c88b7dfad44feb20fe640d731b120465c3a1414ed3c6672376f0dd96bd7fc3c5ee04e654c3cc0473998a7fef9541ecf3e1ad3c1384",
          "sha256": "b1a5ccfc5cfb7a3fe79a3b0b82ba0528e824e3b705a834d4af8be5d85b1a8a1c",
          "sha1": "e000d8f32754029b962abd3a42dacce7e1c334b5",
          "md5": "44704728d9dd3877afa250877c4be7fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.3.aar",
          "url": "camera-lifecycle-1.3.3.aar",
          "size": 22530,
          "sha512": "bb00b714decc3a1995ad60c88b7dfad44feb20fe640d731b120465c3a1414ed3c6672376f0dd96bd7fc3c5ee04e654c3cc0473998a7fef9541ecf3e1ad3c1384",
          "sha256": "b1a5ccfc5cfb7a3fe79a3b0b82ba0528e824e3b705a834d4af8be5d85b1a8a1c",
          "sha1": "e000d8f32754029b962abd3a42dacce7e1c334b5",
          "md5": "44704728d9dd3877afa250877c4be7fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.3-sources.jar",
          "url": "camera-lifecycle-1.3.3-sources.jar",
          "size": 19479,
          "sha512": "99b47bbc7e73be98edc3bf398ba7f6258c388699aa5643aefe24d95275e8428da6ae33a59cd7c387cebcfe5a78aef6d3cc45495421cd19a08fc4aec52c6f67ed",
          "sha256": "d9b8215f54dbb15ed6fffcdfe96cc436fc3897e77c73a2ff986210ba3ebfbd32",
          "sha1": "fadc8569bbf7f44a7a5425643064db16fdd0c131",
          "md5": "4fcb231a866441ec8bbd6253fe25545c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-lifecycle is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.3.3-versionMetadata.json",
          "url": "camera-lifecycle-1.3.3-versionMetadata.json",
          "size": 1358,
          "sha512": "de017fc865d8c0e59acb0d59cff25d123894373175ca9c11fa709e4d7c0e9a282fde4b860389a7cd48f8ee57c85d7ef36ec9abf551844e73c2ee1e8a3daf8a03",
          "sha256": "aa97aabd228be4aae8efe875b7a5c65b4b671f1726412abee00db90e78a46e19",
          "sha1": "0ac1138620422bdcfc2cd21b2ec4769035becc28",
          "md5": "57229101ad1e7b634c0a1f50dfe4715c"
        }
      ]
    }
  ]
}