{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.3.3.aar",
          "url": "camera-view-1.3.3.aar",
          "size": 86361,
          "sha512": "0c20fbbcafdb73433f1ef8a41387791458eaf471300fe83235ae8296f1980507f483c2725016c6e34047149b6b2307650931b3ad8ad2c8984d237c0e8ffa8096",
          "sha256": "931d24b7306c4d7dc8aff250c0a76aff4a773f97849786ea5715252097b224e8",
          "sha1": "3d18c9aae7b0636b7980134ca2fe0a485800bb24",
          "md5": "963b3f1eb0e3f0fbbc5cf792b0ce29fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.3.3.aar",
          "url": "camera-view-1.3.3.aar",
          "size": 86361,
          "sha512": "0c20fbbcafdb73433f1ef8a41387791458eaf471300fe83235ae8296f1980507f483c2725016c6e34047149b6b2307650931b3ad8ad2c8984d237c0e8ffa8096",
          "sha256": "931d24b7306c4d7dc8aff250c0a76aff4a773f97849786ea5715252097b224e8",
          "sha1": "3d18c9aae7b0636b7980134ca2fe0a485800bb24",
          "md5": "963b3f1eb0e3f0fbbc5cf792b0ce29fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.3.3-sources.jar",
          "url": "camera-view-1.3.3-sources.jar",
          "size": 72924,
          "sha512": "3857ac3e19ba315a83c2968c6bb5236bbe16b0584bdc32138c4b3ddf1cf3aa1d02ba8df9f2bc63126cf74cdc110af4f83d5e90d3d89ceecc3f83cecbd456af21",
          "sha256": "d768ca0b9e136afb12b0ca8f78333d16ca390f518948d6920d50f9267b978406",
          "sha1": "21ac156d47bc20eff4d7495751a8b3ec85198aca",
          "md5": "d3b7f478095e1b95c2cba9e19e207249"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.3.3"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.3.3-versionMetadata.json",
          "url": "camera-view-1.3.3-versionMetadata.json",
          "size": 12199,
          "sha512": "573b07569526670ad9f892de4c563d97896dc6fe9b69cfcc25144efd9d6bcb34a28afdb801694bb948b2f8bc3011c8eac833bbd271d18c13bb635ae0942f7b61",
          "sha256": "f4803a74b50bc26a59fe174ee5dd9f7e38a0487f68e241dfce94f5639389d37f",
          "sha1": "a854ea452dd2720f9cf2656658e197f5eb3fb9f7",
          "md5": "df135b85e8fa7d08d6bf60d7a4206407"
        }
      ]
    }
  ]
}